Final Review.
virtual-labs/exp-specific-gravity-iiith pull request #1
Opened 2021-06-10 21:40 UTC by SRDewan

Note that i know that there are very few questions in the quizzes but SME said it is very hard to make questions for this particular concept.

2021-06-12 04:26 UTC, raj-vlabs requested changes

2021-06-12 04:26 UTC, raj-vlabs commented on experiment/posttest.json
> +			"question": "1. For determing the specific gravity of soil solids, using a pycnometer of 500 cc, the following data is available: Weight of dry empty pycnometer = 125 g; Weight of dried soil and p
Spelling mistake

2021-06-12 04:26 UTC, raj-vlabs commented on experiment/posttest.json
> +				"d": ""
How is the learner expected to calculate this? If there's a formula, that formula can be given as the explanation for the correct answer. If there's no way to calculate then how the learner is expected to answer this?

2021-06-12 04:26 UTC, raj-vlabs commented on experiment/pretest.json
> +				"d": ""
The proper definition of pycnometer can be given as the explanation for the correct option. For the other options, the explanation can contain either/both of the two:
1. Why pycnometer cannot be used for this measurement
2. Which device/method is better suited for their measurement

2021-06-12 04:26 UTC, raj-vlabs commented on experiment/pretest.json
> +			"question": "2. The weight of a pycnometer containing 400 g (W1) sand and water full to the top is 2150 g (W2). The weight of pycnometer full of clean water is 1950 g (W3). If the specific gravity
Why would a question similar to one in the posttest be in pretest? Does this test the prerequisite for this experiment or the learning from this experiment?

2021-06-12 04:26 UTC, raj-vlabs commented on experiment/simulation/index.html
> +		<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/virtual-labs/virtual-style@0.0.5-b/css/style.min.css">
If you are using the vlabs library, you do not need to separately import Bulma.

2021-06-20 11:09 UTC, SRDewan commented on experiment/simulation/index.html
> +		<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/virtual-labs/virtual-style@0.0.5-b/css/style.min.css">
Apparently I do as when I don't quite a bit of the formatting disappears.

2021-06-20 11:16 UTC, SRDewan commented on experiment/pretest.json
> +			"question": "2. The weight of a pycnometer containing 400 g (W1) sand and water full to the top is 2150 g (W2). The weight of pycnometer full of clean water is 1950 g (W3). If the specific gravity
This question isnt the same as the posttest question. This involves a concept from an earlier experiment too and sort of forms the prerequisite by an indirect application of the formula from the current theory too.

2021-06-20 11:51 UTC, SRDewan commented on experiment/pretest.json
> +				"d": ""
Am not sure of the explanations. Will ask SME.

2021-06-28 15:52 UTC, raj-vlabs requested changes
Please be consistent in your choice of the quote character (' vs ")

2021-06-28 15:52 UTC, raj-vlabs commented on experiment/simulation/index.html
> +		<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/virtual-labs/virtual-style@0.0.5-b/css/style.min.css">
This should not happen. Please talk to Shlok to resolve this. If required, pull me in.

2021-06-28 15:52 UTC, raj-vlabs commented on experiment/simulation/index.html
> +						<div class="slidecontainer">
Where is slidecontainer defined?

2021-06-28 15:52 UTC, raj-vlabs commented on experiment/simulation/index.html
> +		<div class="columns is-centered is-variable is-1-mobile is-flex is-flex-wrap-wrap workspace">
Is is-1-mobile a valid class name? Why are we using it here?

2021-06-28 15:52 UTC, raj-vlabs commented on experiment/simulation/js/main.js
> +							return val != "soil" && val != "water";
Are we using != because we are expecting some implicit conversions here? Usually we prefer the strict version !==

2021-06-28 15:52 UTC, raj-vlabs commented on experiment/simulation/js/main.js
> +		if(translate[0] != 0 || translate[1] != 0)
Are we using != because we are expecting some implicit conversions here? Usually we prefer the strict version !==

2021-07-06 17:31 UTC, raj-vlabs approved these changes

2021-07-06 17:31 UTC, merged